/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pointofsale;


import com.sun.glass.ui.Window.Level;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.logging.Logger;
import java.sql.*;
import java.io.*;  
 
/**
 *
 * @author Irfan
 */
public class LoginMenu extends javax.swing.JFrame {
    
   
    
    java.sql.Connection conn=null;
ResultSet rs=null;
Statement st;
 private PointOfSaleSystem frame;
    private static final String USERNAME="root";
 private static final String PASSWORD="";
 private static final String CONN_STRING=
"jdbc:mysql://localhost:3306/posjava";  

    /**
     * Creates new form LoginMenu
     */
    public LoginMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jtextField2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POS CAFE SYSTEM");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 51));
        jLabel1.setText("USERNAME:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 75, 115, 63));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("PASSWORD:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 115, 28));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 149, -1));

        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
                enter(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 217, 97, 53));

        jtextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextField2ActionPerformed(evt);
            }
        });
        jtextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtextField2KeyPressed(evt);
            }
        });
        getContentPane().add(jtextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 149, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("          CAFE POS SYSTEM");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 360, 80));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 260, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Java Text\\cafe.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String username=jTextField1.getText();
    String password=jtextField2.getText();
    String admin="1";
    String cashier="2";
  
    try{
        
     conn=DriverManager.getConnection(CONN_STRING,USERNAME,PASSWORD);
        
    st = (Statement)conn.createStatement();
    rs = st.executeQuery("Select * from useraccount");
    while(rs.next())
    {
        if(rs.getString(3).equals(username) && rs.getString(4).equals(password) && rs.getString(6).equals(admin)){
            //If login are matched program will open up
    PointOfSaleSystem view=new PointOfSaleSystem();
            
    AdminPanel view2=new AdminPanel();
    view.setVisible(true); 
    view.setTitle("Welcome, " +username);
    view2.setTitle("Welcome, " +username);
   
        setVisible(false);
         
        }   
     
       
        else if(rs.getString(3).equals(username) && rs.getString(4).equals(password) && rs.getString(6).equals(cashier)){
             PointOfSaleSystem view=new PointOfSaleSystem();
   
    view.jLabel26.setText(rs.getString(1));         
    view.setVisible(true); 
    view.jMenu5.setVisible(false);
     view.jMenu6.setVisible(false);
     
     
    view.setTitle("Welcome, " +username);
   
    setVisible(false);
        }
            jLabel5.setText("Wrong Username or Password.");
    
                   }
    }catch(SQLException ex){
       
          System.err.println(ex);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed

    }//GEN-LAST:event_jButton1KeyPressed

    private void enter(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enter
       
    }//GEN-LAST:event_enter

    private void jtextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextField2ActionPerformed
 
    }//GEN-LAST:event_jtextField2ActionPerformed

    private void jtextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtextField2KeyPressed
    if(evt.getKeyCode()==KeyEvent.VK_ENTER){
                String username=jTextField1.getText();
    String password=jtextField2.getText();
    String admin="1";
    String cashier="2";
  
    try{
        
     conn=DriverManager.getConnection(CONN_STRING,USERNAME,PASSWORD);
        
    st = (Statement)conn.createStatement();
    rs = st.executeQuery("Select * from useraccount");
    while(rs.next())
    {
        if(rs.getString(3).equals(username) && rs.getString(4).equals(password) && rs.getString(6).equals(admin)){
            //If login are matched program will open up
    PointOfSaleSystem view=new PointOfSaleSystem();
            
    AdminPanel view2=new AdminPanel();
    view.setVisible(true); 
    view.setTitle("Welcome, " +username);
    view2.setTitle("Welcome, " +username);
   
        setVisible(false);
         
        }   
     
       
        else if(rs.getString(3).equals(username) && rs.getString(4).equals(password) && rs.getString(6).equals(cashier)){
             PointOfSaleSystem view=new PointOfSaleSystem();
    view.setVisible(true); 
    view.jMenu5.setVisible(false);
     view.jMenu6.setVisible(false);
     
     
    view.setTitle("Welcome, " +username);
   
    setVisible(false);
        }
            jLabel5.setText("Wrong Username or Password.");
    
                   }
    }catch(SQLException ex){
       
          System.err.println(ex);
    }
}else{
    
}
    }//GEN-LAST:event_jtextField2KeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
if(evt.getKeyCode()==KeyEvent.VK_ENTER){
                String username=jTextField1.getText();
    String password=jtextField2.getText();
    String admin="1";
    String cashier="2";
  
    try{
        
     conn=DriverManager.getConnection(CONN_STRING,USERNAME,PASSWORD);
        
    st = (Statement)conn.createStatement();
    rs = st.executeQuery("Select * from useraccount");
    while(rs.next())
    {
        if(rs.getString(3).equals(username) && rs.getString(4).equals(password) && rs.getString(6).equals(admin)){
            //If login are matched program will open up
    PointOfSaleSystem view=new PointOfSaleSystem();
            
    AdminPanel view2=new AdminPanel();
    view.setVisible(true); 
    view.setTitle("Welcome, " +username);
    view2.setTitle("Welcome, " +username);
   
        setVisible(false);
         
        }   
     
       
        else if(rs.getString(3).equals(username) && rs.getString(4).equals(password) && rs.getString(6).equals(cashier)){
             PointOfSaleSystem view=new PointOfSaleSystem();
    view.setVisible(true); 
    view.jMenu5.setVisible(false);
     view.jMenu6.setVisible(false);
     
     
    view.setTitle("Welcome, " +username);
   
    setVisible(false);
        }
            jLabel5.setText("Wrong Username or Password.");
    
                   }
    }catch(SQLException ex){
       
          System.err.println(ex);
    }
}else{
    
}
    }                                      

    private void CloseMe(){
    WindowEvent meClose =new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(meClose);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginMenu().setVisible(true);
            }
        });
    }//GEN-LAST:event_jTextField1KeyPressed

   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField jtextField2;
    // End of variables declaration//GEN-END:variables
}
